name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@main

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: glowing-ink
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: maven

      - name: Build and publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.REPO_PASSWORD }}